name = "techflunky"
compatibility_date = "2024-01-01"
main = "src/workers/cron.ts"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "techflunky-db"
database_id = "330b8406-f05f-4e5b-966a-a58fcd2ba3d1"

# R2 Storage binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "techflunky-assets"

# KV namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "31831cdf293546b992aefcfc0edb139f"
preview_id = "31831cdf293546b992aefcfc0edb139f"

# Environment variables (add to .dev.vars for local development)
[vars]
ENVIRONMENT = "production"
SITE_URL = "https://techflunky.com"

# Cron triggers for automated tasks
[triggers]
crons = [
  "*/15 * * * *",  # Every 15 minutes - AI analysis queue
  "0 * * * *",     # Every hour - cleanup tasks
  "0 9 * * *",     # Daily at 9 AM UTC - analytics
  "0 0 * * 1",     # Weekly on Mondays - affiliate payouts
  "0 0 1 * *"      # Monthly on 1st - reports
]

# Analytics Engine for tracking
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Workers routes for API
[[routes]]
pattern = "api.techflunky.com/*"
zone_name = "techflunky.com"

# Compatibility flags
compatibility_flags = ["nodejs_compat"]
