# Cloudflare Pages configuration
name = "techflunky"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Note: For Cloudflare Pages, bindings are configured through the dashboard
# The following are reference configurations for development and dashboard setup:

# Environment variables for development
[vars]
ENVIRONMENT = "production"
SITE_URL = "https://techflunky.com"

# Required bindings to configure in Cloudflare dashboard:
# - AI binding: "AI"
# - D1 database: "DB" (database: techflunky-db)
# - R2 bucket: "BUCKET" (bucket: techflunky-assets)
# - KV namespace: "CACHE"
# - Analytics Engine: "ANALYTICS"

# D1 database bindings
[[d1_databases]]
binding = "DB"
database_name = "techflunky-db"
database_id = "330b8406-f05f-4e5b-966a-a58fcd2ba3d1"

# For development with wrangler pages dev:
# wrangler pages dev dist --d1 DB=techflunky-db --r2 BUCKET=techflunky-assets --kv CACHE --ai AI=@cf/meta/llama-3.1-70b-instruct
