# Cloudflare Pages configuration
name = "techflunky"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Environment variables
[vars]
ENVIRONMENT = "production"
SITE_URL = "https://techflunky.com"

# D1 database bindings
[[d1_databases]]
binding = "DB"
database_name = "techflunky-db"
database_id = "330b8406-f05f-4e5b-966a-a58fcd2ba3d1"

# R2 bucket bindings
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "techflunky-assets"

# KV namespace bindings
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"

# Analytics Engine bindings
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# AI bindings
[ai]
binding = "AI"
