# TechFlunky User Worker for Workers for Platforms
name = "techflunky-user"
main = "index.ts"
compatibility_date = "2024-01-01"

# This Worker will be deployed as a user Worker in the dispatch namespace

# Environment variables
[vars]
ENVIRONMENT = "production"
SITE_URL = "https://techflunky.com"

# Note: Resource bindings (DB, AI, BUCKET, etc.) will be provided by the dispatch Worker
# when this Worker is invoked through Workers for Platforms

# Development configuration
[env.development]
[env.development.vars]
ENVIRONMENT = "development"
SITE_URL = "http://localhost:4321"

# For local development, include resource bindings
[env.development.d1_databases]
binding = "DB"
database_name = "techflunky-db"
database_id = "330b8406-f05f-4e5b-966a-a58fcd2ba3d1"

# Production secrets will be inherited from dispatch Worker
# - STRIPE_SECRET_KEY
# - STRIPE_WEBHOOK_SECRET_TEST
# - STRIPE_WEBHOOK_SECRET_LIVE
# - AUTIMIND_STRIPE_KEY