name: Feature Request
description: Suggest a new feature for TechFlunky
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        We love hearing from the indie developer community! Your ideas help shape TechFlunky's future.

  - type: input
    id: contact
    attributes:
      label: Contact Details (Optional)
      description: How can we reach you if we need clarification?
      placeholder: ex. email@example.com or @username
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: What problem would this feature solve?
      description: Describe the pain point you're experiencing
      placeholder: As an indie developer, I find it frustrating when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe your ideal solution
      description: What would you like to see happen?
      placeholder: I would love to see...
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Who would benefit from this feature?
      multiple: true
      options:
        - Developers/Sellers
        - Entrepreneurs/Buyers
        - Investors
        - Platform Administrators
        - All Users
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - "Critical - Blocking my success"
        - "High - Would significantly improve my experience"
        - "Medium - Nice to have"
        - "Low - Minor convenience"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you considered?
      description: Are there workarounds or other approaches you've tried?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Mockups, examples, or related features from other platforms
    validations:
      required: false

  - type: dropdown
    id: willing-to-help
    attributes:
      label: Would you be willing to help implement this?
      options:
        - "Yes, I can contribute code"
        - "Yes, I can help with design/planning"
        - "Yes, I can help test"
        - "No, but I'd love to see it implemented"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to our community guidelines
      options:
        - label: I agree to follow TechFlunky's Code of Conduct
          required: true